// prettier-ignore
export default {
    signTransactionsOverviewContainer: 'sign-transactions-overview-container drt:flex drt:flex-col drt:w-full drt:bg-accent-variant drt:rounded-2xl drt:overflow-hidden',
    signTransactionsOverviewContent: 'sig-transactions-overview-content drt:flex drt:flex-col drt:gap-1 drt:p-1 drt:relative',
    signTransactionsDetailRow: 'sign-transactions-detail-row drt:flex drt:items-center drt:py-4 drt:px-5 drt:bg-secondary drt:relative drt:overflow-hidden drt:min-h-20',
    signTransactionsAmountRow: 'sign-transactions-amount-row drt:rounded-xl',
    signTransactionsInteractorRow: 'sign-transactions-interactor-row drt:rounded-xl drt:relative drt:z-5',
    signTransactionsActionRow: 'sign-transactions-action-row drt:pt-7 drt:px-5 drt:pb-2 drt:rounded-bl-xl drt:min-h-14 drt:-mt-6 drt:relative  drt:before:absolute drt:before:opacity-60 drt:before:top-0 drt:before:bottom-0 drt:before:left-0 drt:before:right-0 drt:before:transition-all drt:before:duration-200 drt:before:rounded-b-xl drt:before:pointer-events-none drt:before:ease-in-out drt:before:content-[""] drt:before:bg-tertiary',
    signTransactionsDetailLabel: 'sign-transactions-detail-label drt:text-secondary-text drt:text-sm drt:font-normal drt:leading-5 drt:relative drt:z-1',
    signTransactionsAmountDisplay: 'sign-transactions-amount-display drt:flex drt:items-center drt:ml-auto drt:gap-3 drt:z-1',
    signTransactionsAmountValueContainer: 'sign-transactions-amount-value-container drt:flex drt:flex-col drt:items-end drt:gap-1',
    signTransactionsAmountValue: 'sign-transactions-amount-value drt:text-xl drt:font-medium drt:text-primary drt:-tracking-[0.24px] drt:leading-6 drt:text-right drt:whitespace-nowrap',
    signTransactionsIdentifier: 'sign-transactions-identifier drt:text-sm drt:text-primary',
    signTransactionsUsdValue: 'sign-transactions-usd-value drt:text-sm drt:text-secondary-text',
    signTransactionsTokenIcon: 'sign-transactions-token-icon drt:w-10 drt:h-10 drt:rounded-xs drt:overflow-hidden drt:border drt:border-neutral-700',
    signTransactionsTokenIconImg: 'sign-transactions-token-icon-img drt:w-full drt:h-full drt:object-cover',
    signTransactionsInteractorInfo: 'sign-transactions-interactor-info drt:flex drt:items-center drt:ml-auto drt:gap-3 drt:z-1',
    signTransactionsInteractorIcon: 'sign-transactions-interactor-icon drt:w-6 drt:h-6 drt:rounded-full drt:overflow-hidden',
    signTransactionsInteractorIconImg: 'sign-transactions-interactor-icon-img drt:w-full drt:h-full drt:object-cover',
    signTransactionsInteractorName: 'sign-transactions-interactor-name drt:text-base drt:font-normal drt:text-primary drt:-tracking-[0.16px] drt:leading-5 drt:!max-w-65',
    signTransactionsDirection: 'sign-transactions-direction drt:absolute drt:flex drt:flex-col drt:items-center drt:justify-center drt:w-6 drt:h-6 drt:rounded-full drt:left-5 drt:z-10 drt:bg-accent-variant',
    signTransactionsDirectionIcon: 'sign-transactions-direction-icon drt:flex drt:flex-col drt:items-center drt:gap-px',
    signTransactionsDirectionIconArrow: 'sign-transactions-direction-icon-arrow drt:flex drt:items-center drt:justify-center drt:relative drt:shrink-0 drt:w-3 drt:basis-auto drt:-mt-1 drt:-mb-0.5 drt:text-secondary-text',
    signTransactionsDirectionIconArrowDown: 'sign-transactions-direction-icon-arrow-down drt:-mt-0.5 drt:-mb-1 drt:order-1',
    signTransactionsDirectionIconDot: 'sign-transactions-direction-icon-dot drt:relative drt:rounded-full drt:w-0.5 drt:h-0.5 drt:bg-secondary-text',
    signTransactionsActionValue: 'sign-transactions-action-value drt:ml-auto drt:text-sm drt:font-medium drt:text-secondary-text drt:relative drt:z-1',
    signTransactionsFeeContainer: 'sign-transactions-fee-container drt:py-2 drt:px-6',
    signTransactionsFeeRow: 'sign-transactions-fee-row drt:flex drt:items-center drt:justify-between drt:py-3 drt:px-0',
    signTransactionsFeeLabelContainer: 'sign-transactions-fee-label-container drt:flex drt:items-center drt:gap-1',
    signTransactionsFeeLabel: 'sign-transactions-fee-label drt:text-secondary-text drt:text-sm drt:font-normal drt:leading-5',
    signTransactionsInfoIcon: 'sign-transactions-info-icon drt:w-3.5 drt:h-3.5 drt:relative drt:before:content-["ⓘ"] drt:before:text-sm drt:before:text-secondary-text drt:before:absolute drt:before:-top-0.5 drt:before:left-0',
    signTransactionsFeeValue: 'sign-transactions-fee-value drt:text-primary drt:text-sm drt:font-normal drt:leading-5'
} satisfies Record<string, string>;
