/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IAddressTableData } from "./types/address-table.types";
import { ButtonSizeEnum, ButtonVariantEnum } from "./common/Button/button.types";
import { CustomToastType, IComponentToast, ISimpleToast } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
import { IConfirmScreenData, IConnectScreenData, ILedgerConnectPanelData } from "./components/functional/ledger-connect/ledger-connect.types";
import { IEventBus } from "./utils/EventBus";
import { LocalJSX as JSX } from "@stencil/core";
import { ITransactionListItem } from "./components/functional/notifications-feed/components/TransactionListItem/transactionListItem.types";
import { IToastDataState, ITransactionProgressState } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
import { TransactionStatusEnum } from "./constants/transactionStatus.enum";
import { TransactionRowType } from "./components/controlled/transactions-table/transactions-table.type";
import { IEventBus as IEventBus1, unknown as IWalletConnectPanelData } from "./components.d";
export { IAddressTableData } from "./types/address-table.types";
export { ButtonSizeEnum, ButtonVariantEnum } from "./common/Button/button.types";
export { CustomToastType, IComponentToast, ISimpleToast } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
export { IConfirmScreenData, IConnectScreenData, ILedgerConnectPanelData } from "./components/functional/ledger-connect/ledger-connect.types";
export { IEventBus } from "./utils/EventBus";
export { LocalJSX as JSX } from "@stencil/core";
export { ITransactionListItem } from "./components/functional/notifications-feed/components/TransactionListItem/transactionListItem.types";
export { IToastDataState, ITransactionProgressState } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
export { TransactionStatusEnum } from "./constants/transactionStatus.enum";
export { TransactionRowType } from "./components/controlled/transactions-table/transactions-table.type";
export { IEventBus as IEventBus1, unknown as IWalletConnectPanelData } from "./components.d";
export namespace Components {
    interface DrtAddressTable {
        "accountScreenData": IAddressTableData;
        "selectedIndex": number;
    }
    interface DrtArcExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtArrowRightIcon {
        "class"?: string;
    }
    interface DrtBraveExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtButton {
        /**
          * @default ''
         */
        "class"?: string;
        /**
          * @default ''
         */
        "dataTestId"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'large'
         */
        "size"?: `${ButtonSizeEnum}`;
        /**
          * @default 'primary'
         */
        "variant"?: `${ButtonVariantEnum}`;
    }
    interface DrtCircleInfoIcon {
        "class"?: string;
    }
    interface DrtCopyButton {
        "class"?: string;
        "iconClass"?: string;
        "text": string;
    }
    interface DrtCustomToast {
        "toast": IComponentToast;
    }
    interface DrtDataWithExplorerLink {
        "class"?: string;
        "data": string;
        "dataTestId"?: string;
        "explorerLink": string;
        /**
          * @default true
         */
        "showCopyButton"?: boolean;
        /**
          * @default true
         */
        "showExplorerButton"?: boolean;
        /**
          * @default false
         */
        "withTooltip"?: boolean;
    }
    interface DrtDefaultTransactionIconLarge {
        "class"?: string;
    }
    interface DrtDefaultTransactionIconSmall {
        "class"?: string;
    }
    interface DrtDharitriLogoIcon {
        "class"?: string;
    }
    interface DrtDharitriSymbolIcon {
        "class"?: string;
    }
    interface DrtEdgeExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtExplorerLink {
        "class"?: string;
        "dataTestId"?: string;
        "iconClass"?: string;
        "link": string;
    }
    interface DrtExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtFirefoxExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtFormatAmount {
        "class"?: string;
        "dataTestId"?: string;
        "decimalClass"?: string;
        "isValid": boolean;
        "label"?: string;
        "labelClass"?: string;
        /**
          * @default true
         */
        "showLabel"?: boolean;
        "valueDecimal": string;
        "valueInteger": string;
    }
    interface DrtGenericToast {
        "toast": CustomToastType;
    }
    interface DrtLedgerConfirm {
        "confirmScreenData": IConfirmScreenData;
    }
    interface DrtLedgerConnect {
        /**
          * @default {     accountScreenData: null,     confirmScreenData: null,     connectScreenData: {},   }
         */
        "data": ILedgerConnectPanelData;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface DrtLedgerIcon {
        "class"?: string;
    }
    interface DrtLedgerIntro {
        "connectScreenData"?: IConnectScreenData;
        /**
          * @default false
         */
        "isAwaiting"?: boolean;
    }
    interface DrtLedgerProviderIcon {
        "class"?: string;
    }
    interface DrtMagnifyingGlassIcon {
        "class"?: string;
    }
    interface DrtMetamaskProviderIcon {
        "class"?: string;
    }
    interface DrtNotificationsFeed {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface DrtPasskeyProviderIcon {
        "class"?: string;
    }
    interface DrtPendingTransactionsPanel {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface DrtPreloader {
        "class"?: string;
    }
    interface DrtShardIcon {
        "class"?: string;
        /**
          * @default 0
         */
        "shard": number;
    }
    interface DrtSignTransactionsPanel {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface DrtSimpleToast {
        "toast": ISimpleToast;
    }
    interface DrtSpinnerIcon {
        "class"?: string;
    }
    interface DrtTdharitriDownloadQrIcon {
        /**
          * @default ''
         */
        "class"?: string;
    }
    interface DrtTdharitriQrCodePreloader {
        "class"?: string;
    }
    interface DrtToastList {
        "getEventBus": () => Promise<IEventBus>;
    }
    interface DrtTooltip {
        "class"?: string;
        /**
          * @default 'top'
         */
        "position": 'top' | 'bottom';
        "trigger": HTMLElement;
        /**
          * @default false
         */
        "triggerOnClick"?: boolean;
    }
    interface DrtTransactionToast {
        "fullWidth"?: boolean;
        /**
          * @default ''
         */
        "processedTransactionsStatus": string | JSX.Element;
        "toastDataState": IToastDataState;
        /**
          * @default ''
         */
        "toastId": string;
        "transactionProgressState"?: ITransactionProgressState;
        /**
          * @default []
         */
        "transactions": ITransactionListItem[];
        "wrapperClass": string;
    }
    interface DrtTransactionToastContent {
        "fullWidth"?: boolean;
        "processedTransactionsStatus"?: string | JSX.Element;
        "toastDataState": IToastDataState;
        "transactions": ITransactionListItem[];
    }
    interface DrtTransactionToastDetails {
        /**
          * @default 5
         */
        "maxShownTransactions": number;
        "processedTransactionsStatus"?: string | JSX.Element;
        "transactionClass": string;
        "transactions"?: ITransactionListItem[];
    }
    interface DrtTransactionToastDetailsBody {
        "hash": string;
        "index": string;
        "link": string;
        "status"?: `${TransactionStatusEnum}`;
        /**
          * @default 'transaction-details-list-item'
         */
        "transactionClass"?: string;
    }
    interface DrtTransactionToastProgress {
        "endTime"?: number;
        "isStatusPending"?: boolean;
        "startTime"?: number;
        "toastId"?: string;
    }
    interface DrtTransactionsTable {
        "class"?: string;
        "transactions": TransactionRowType[];
    }
    interface DrtTrim {
        "class"?: string;
        /**
          * @default DataTestIdsEnum.trim
         */
        "dataTestId"?: string;
        "text": string;
    }
    interface DrtUnlockPanel {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface DrtWalletConnect {
        /**
          * @default { wcURI: '' }
         */
        "data": IWalletConnectPanelData;
        "getEventBus": () => Promise<IEventBus>;
        /**
          * @default ''
         */
        "qrCodeSvg": string;
    }
    interface DrtWalletConnectAppGalleryIcon {
        "class"?: string;
    }
    interface DrtWalletConnectAppStoreIcon {
        "class"?: string;
    }
    interface DrtWalletConnectDownload {
        "class"?: string;
    }
    interface DrtWalletConnectGooglePlayIcon {
        "class"?: string;
    }
    interface DrtWalletConnectScan {
        "class"?: string;
        /**
          * @default ''
         */
        "qrCodeSvg": string;
        /**
          * @default ''
         */
        "walletConnectDeepLink"?: string;
    }
    interface DrtWalletProviderIcon {
        "class"?: string;
    }
}
export interface DrtAddressTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtAddressTableElement;
}
export interface DrtButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtButtonElement;
}
export interface DrtCustomToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtCustomToastElement;
}
export interface DrtGenericToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtGenericToastElement;
}
export interface DrtLedgerIntroCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtLedgerIntroElement;
}
export interface DrtSimpleToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtSimpleToastElement;
}
export interface DrtTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtTooltipElement;
}
export interface DrtTransactionToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtTransactionToastElement;
}
export interface DrtTransactionToastContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtTransactionToastContentElement;
}
export interface DrtWalletConnectScanCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrtWalletConnectScanElement;
}
declare global {
    interface HTMLDrtAddressTableElementEventMap {
        "accessWallet": any;
        "selectAccount": any;
        "pageChange": number;
    }
    interface HTMLDrtAddressTableElement extends Components.DrtAddressTable, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtAddressTableElementEventMap>(type: K, listener: (this: HTMLDrtAddressTableElement, ev: DrtAddressTableCustomEvent<HTMLDrtAddressTableElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtAddressTableElementEventMap>(type: K, listener: (this: HTMLDrtAddressTableElement, ev: DrtAddressTableCustomEvent<HTMLDrtAddressTableElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtAddressTableElement: {
        prototype: HTMLDrtAddressTableElement;
        new (): HTMLDrtAddressTableElement;
    };
    interface HTMLDrtArcExtensionProviderIconElement extends Components.DrtArcExtensionProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtArcExtensionProviderIconElement: {
        prototype: HTMLDrtArcExtensionProviderIconElement;
        new (): HTMLDrtArcExtensionProviderIconElement;
    };
    interface HTMLDrtArrowRightIconElement extends Components.DrtArrowRightIcon, HTMLStencilElement {
    }
    var HTMLDrtArrowRightIconElement: {
        prototype: HTMLDrtArrowRightIconElement;
        new (): HTMLDrtArrowRightIconElement;
    };
    interface HTMLDrtBraveExtensionProviderIconElement extends Components.DrtBraveExtensionProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtBraveExtensionProviderIconElement: {
        prototype: HTMLDrtBraveExtensionProviderIconElement;
        new (): HTMLDrtBraveExtensionProviderIconElement;
    };
    interface HTMLDrtButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLDrtButtonElement extends Components.DrtButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtButtonElementEventMap>(type: K, listener: (this: HTMLDrtButtonElement, ev: DrtButtonCustomEvent<HTMLDrtButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtButtonElementEventMap>(type: K, listener: (this: HTMLDrtButtonElement, ev: DrtButtonCustomEvent<HTMLDrtButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtButtonElement: {
        prototype: HTMLDrtButtonElement;
        new (): HTMLDrtButtonElement;
    };
    interface HTMLDrtCircleInfoIconElement extends Components.DrtCircleInfoIcon, HTMLStencilElement {
    }
    var HTMLDrtCircleInfoIconElement: {
        prototype: HTMLDrtCircleInfoIconElement;
        new (): HTMLDrtCircleInfoIconElement;
    };
    interface HTMLDrtCopyButtonElement extends Components.DrtCopyButton, HTMLStencilElement {
    }
    var HTMLDrtCopyButtonElement: {
        prototype: HTMLDrtCopyButtonElement;
        new (): HTMLDrtCopyButtonElement;
    };
    interface HTMLDrtCustomToastElementEventMap {
        "deleteToast": string;
    }
    interface HTMLDrtCustomToastElement extends Components.DrtCustomToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtCustomToastElementEventMap>(type: K, listener: (this: HTMLDrtCustomToastElement, ev: DrtCustomToastCustomEvent<HTMLDrtCustomToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtCustomToastElementEventMap>(type: K, listener: (this: HTMLDrtCustomToastElement, ev: DrtCustomToastCustomEvent<HTMLDrtCustomToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtCustomToastElement: {
        prototype: HTMLDrtCustomToastElement;
        new (): HTMLDrtCustomToastElement;
    };
    interface HTMLDrtDataWithExplorerLinkElement extends Components.DrtDataWithExplorerLink, HTMLStencilElement {
    }
    var HTMLDrtDataWithExplorerLinkElement: {
        prototype: HTMLDrtDataWithExplorerLinkElement;
        new (): HTMLDrtDataWithExplorerLinkElement;
    };
    interface HTMLDrtDefaultTransactionIconLargeElement extends Components.DrtDefaultTransactionIconLarge, HTMLStencilElement {
    }
    var HTMLDrtDefaultTransactionIconLargeElement: {
        prototype: HTMLDrtDefaultTransactionIconLargeElement;
        new (): HTMLDrtDefaultTransactionIconLargeElement;
    };
    interface HTMLDrtDefaultTransactionIconSmallElement extends Components.DrtDefaultTransactionIconSmall, HTMLStencilElement {
    }
    var HTMLDrtDefaultTransactionIconSmallElement: {
        prototype: HTMLDrtDefaultTransactionIconSmallElement;
        new (): HTMLDrtDefaultTransactionIconSmallElement;
    };
    interface HTMLDrtDharitriLogoIconElement extends Components.DrtDharitriLogoIcon, HTMLStencilElement {
    }
    var HTMLDrtDharitriLogoIconElement: {
        prototype: HTMLDrtDharitriLogoIconElement;
        new (): HTMLDrtDharitriLogoIconElement;
    };
    interface HTMLDrtDharitriSymbolIconElement extends Components.DrtDharitriSymbolIcon, HTMLStencilElement {
    }
    var HTMLDrtDharitriSymbolIconElement: {
        prototype: HTMLDrtDharitriSymbolIconElement;
        new (): HTMLDrtDharitriSymbolIconElement;
    };
    interface HTMLDrtEdgeExtensionProviderIconElement extends Components.DrtEdgeExtensionProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtEdgeExtensionProviderIconElement: {
        prototype: HTMLDrtEdgeExtensionProviderIconElement;
        new (): HTMLDrtEdgeExtensionProviderIconElement;
    };
    interface HTMLDrtExplorerLinkElement extends Components.DrtExplorerLink, HTMLStencilElement {
    }
    var HTMLDrtExplorerLinkElement: {
        prototype: HTMLDrtExplorerLinkElement;
        new (): HTMLDrtExplorerLinkElement;
    };
    interface HTMLDrtExtensionProviderIconElement extends Components.DrtExtensionProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtExtensionProviderIconElement: {
        prototype: HTMLDrtExtensionProviderIconElement;
        new (): HTMLDrtExtensionProviderIconElement;
    };
    interface HTMLDrtFirefoxExtensionProviderIconElement extends Components.DrtFirefoxExtensionProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtFirefoxExtensionProviderIconElement: {
        prototype: HTMLDrtFirefoxExtensionProviderIconElement;
        new (): HTMLDrtFirefoxExtensionProviderIconElement;
    };
    interface HTMLDrtFormatAmountElement extends Components.DrtFormatAmount, HTMLStencilElement {
    }
    var HTMLDrtFormatAmountElement: {
        prototype: HTMLDrtFormatAmountElement;
        new (): HTMLDrtFormatAmountElement;
    };
    interface HTMLDrtGenericToastElementEventMap {
        "deleteToast": string;
    }
    interface HTMLDrtGenericToastElement extends Components.DrtGenericToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtGenericToastElementEventMap>(type: K, listener: (this: HTMLDrtGenericToastElement, ev: DrtGenericToastCustomEvent<HTMLDrtGenericToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtGenericToastElementEventMap>(type: K, listener: (this: HTMLDrtGenericToastElement, ev: DrtGenericToastCustomEvent<HTMLDrtGenericToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtGenericToastElement: {
        prototype: HTMLDrtGenericToastElement;
        new (): HTMLDrtGenericToastElement;
    };
    interface HTMLDrtLedgerConfirmElement extends Components.DrtLedgerConfirm, HTMLStencilElement {
    }
    var HTMLDrtLedgerConfirmElement: {
        prototype: HTMLDrtLedgerConfirmElement;
        new (): HTMLDrtLedgerConfirmElement;
    };
    interface HTMLDrtLedgerConnectElement extends Components.DrtLedgerConnect, HTMLStencilElement {
    }
    var HTMLDrtLedgerConnectElement: {
        prototype: HTMLDrtLedgerConnectElement;
        new (): HTMLDrtLedgerConnectElement;
    };
    interface HTMLDrtLedgerIconElement extends Components.DrtLedgerIcon, HTMLStencilElement {
    }
    var HTMLDrtLedgerIconElement: {
        prototype: HTMLDrtLedgerIconElement;
        new (): HTMLDrtLedgerIconElement;
    };
    interface HTMLDrtLedgerIntroElementEventMap {
        "connect": any;
    }
    interface HTMLDrtLedgerIntroElement extends Components.DrtLedgerIntro, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtLedgerIntroElementEventMap>(type: K, listener: (this: HTMLDrtLedgerIntroElement, ev: DrtLedgerIntroCustomEvent<HTMLDrtLedgerIntroElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtLedgerIntroElementEventMap>(type: K, listener: (this: HTMLDrtLedgerIntroElement, ev: DrtLedgerIntroCustomEvent<HTMLDrtLedgerIntroElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtLedgerIntroElement: {
        prototype: HTMLDrtLedgerIntroElement;
        new (): HTMLDrtLedgerIntroElement;
    };
    interface HTMLDrtLedgerProviderIconElement extends Components.DrtLedgerProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtLedgerProviderIconElement: {
        prototype: HTMLDrtLedgerProviderIconElement;
        new (): HTMLDrtLedgerProviderIconElement;
    };
    interface HTMLDrtMagnifyingGlassIconElement extends Components.DrtMagnifyingGlassIcon, HTMLStencilElement {
    }
    var HTMLDrtMagnifyingGlassIconElement: {
        prototype: HTMLDrtMagnifyingGlassIconElement;
        new (): HTMLDrtMagnifyingGlassIconElement;
    };
    interface HTMLDrtMetamaskProviderIconElement extends Components.DrtMetamaskProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtMetamaskProviderIconElement: {
        prototype: HTMLDrtMetamaskProviderIconElement;
        new (): HTMLDrtMetamaskProviderIconElement;
    };
    interface HTMLDrtNotificationsFeedElement extends Components.DrtNotificationsFeed, HTMLStencilElement {
    }
    var HTMLDrtNotificationsFeedElement: {
        prototype: HTMLDrtNotificationsFeedElement;
        new (): HTMLDrtNotificationsFeedElement;
    };
    interface HTMLDrtPasskeyProviderIconElement extends Components.DrtPasskeyProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtPasskeyProviderIconElement: {
        prototype: HTMLDrtPasskeyProviderIconElement;
        new (): HTMLDrtPasskeyProviderIconElement;
    };
    interface HTMLDrtPendingTransactionsPanelElement extends Components.DrtPendingTransactionsPanel, HTMLStencilElement {
    }
    var HTMLDrtPendingTransactionsPanelElement: {
        prototype: HTMLDrtPendingTransactionsPanelElement;
        new (): HTMLDrtPendingTransactionsPanelElement;
    };
    interface HTMLDrtPreloaderElement extends Components.DrtPreloader, HTMLStencilElement {
    }
    var HTMLDrtPreloaderElement: {
        prototype: HTMLDrtPreloaderElement;
        new (): HTMLDrtPreloaderElement;
    };
    interface HTMLDrtShardIconElement extends Components.DrtShardIcon, HTMLStencilElement {
    }
    var HTMLDrtShardIconElement: {
        prototype: HTMLDrtShardIconElement;
        new (): HTMLDrtShardIconElement;
    };
    interface HTMLDrtSignTransactionsPanelElement extends Components.DrtSignTransactionsPanel, HTMLStencilElement {
    }
    var HTMLDrtSignTransactionsPanelElement: {
        prototype: HTMLDrtSignTransactionsPanelElement;
        new (): HTMLDrtSignTransactionsPanelElement;
    };
    interface HTMLDrtSimpleToastElementEventMap {
        "deleteToast": void;
    }
    interface HTMLDrtSimpleToastElement extends Components.DrtSimpleToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtSimpleToastElementEventMap>(type: K, listener: (this: HTMLDrtSimpleToastElement, ev: DrtSimpleToastCustomEvent<HTMLDrtSimpleToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtSimpleToastElementEventMap>(type: K, listener: (this: HTMLDrtSimpleToastElement, ev: DrtSimpleToastCustomEvent<HTMLDrtSimpleToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtSimpleToastElement: {
        prototype: HTMLDrtSimpleToastElement;
        new (): HTMLDrtSimpleToastElement;
    };
    interface HTMLDrtSpinnerIconElement extends Components.DrtSpinnerIcon, HTMLStencilElement {
    }
    var HTMLDrtSpinnerIconElement: {
        prototype: HTMLDrtSpinnerIconElement;
        new (): HTMLDrtSpinnerIconElement;
    };
    interface HTMLDrtTdharitriDownloadQrIconElement extends Components.DrtTdharitriDownloadQrIcon, HTMLStencilElement {
    }
    var HTMLDrtTdharitriDownloadQrIconElement: {
        prototype: HTMLDrtTdharitriDownloadQrIconElement;
        new (): HTMLDrtTdharitriDownloadQrIconElement;
    };
    interface HTMLDrtTdharitriQrCodePreloaderElement extends Components.DrtTdharitriQrCodePreloader, HTMLStencilElement {
    }
    var HTMLDrtTdharitriQrCodePreloaderElement: {
        prototype: HTMLDrtTdharitriQrCodePreloaderElement;
        new (): HTMLDrtTdharitriQrCodePreloaderElement;
    };
    interface HTMLDrtToastListElement extends Components.DrtToastList, HTMLStencilElement {
    }
    var HTMLDrtToastListElement: {
        prototype: HTMLDrtToastListElement;
        new (): HTMLDrtToastListElement;
    };
    interface HTMLDrtTooltipElementEventMap {
        "triggerRender": boolean;
    }
    interface HTMLDrtTooltipElement extends Components.DrtTooltip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtTooltipElementEventMap>(type: K, listener: (this: HTMLDrtTooltipElement, ev: DrtTooltipCustomEvent<HTMLDrtTooltipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtTooltipElementEventMap>(type: K, listener: (this: HTMLDrtTooltipElement, ev: DrtTooltipCustomEvent<HTMLDrtTooltipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtTooltipElement: {
        prototype: HTMLDrtTooltipElement;
        new (): HTMLDrtTooltipElement;
    };
    interface HTMLDrtTransactionToastElementEventMap {
        "deleteToast": void;
    }
    interface HTMLDrtTransactionToastElement extends Components.DrtTransactionToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtTransactionToastElementEventMap>(type: K, listener: (this: HTMLDrtTransactionToastElement, ev: DrtTransactionToastCustomEvent<HTMLDrtTransactionToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtTransactionToastElementEventMap>(type: K, listener: (this: HTMLDrtTransactionToastElement, ev: DrtTransactionToastCustomEvent<HTMLDrtTransactionToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtTransactionToastElement: {
        prototype: HTMLDrtTransactionToastElement;
        new (): HTMLDrtTransactionToastElement;
    };
    interface HTMLDrtTransactionToastContentElementEventMap {
        "deleteToast": void;
    }
    interface HTMLDrtTransactionToastContentElement extends Components.DrtTransactionToastContent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtTransactionToastContentElementEventMap>(type: K, listener: (this: HTMLDrtTransactionToastContentElement, ev: DrtTransactionToastContentCustomEvent<HTMLDrtTransactionToastContentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtTransactionToastContentElementEventMap>(type: K, listener: (this: HTMLDrtTransactionToastContentElement, ev: DrtTransactionToastContentCustomEvent<HTMLDrtTransactionToastContentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtTransactionToastContentElement: {
        prototype: HTMLDrtTransactionToastContentElement;
        new (): HTMLDrtTransactionToastContentElement;
    };
    interface HTMLDrtTransactionToastDetailsElement extends Components.DrtTransactionToastDetails, HTMLStencilElement {
    }
    var HTMLDrtTransactionToastDetailsElement: {
        prototype: HTMLDrtTransactionToastDetailsElement;
        new (): HTMLDrtTransactionToastDetailsElement;
    };
    interface HTMLDrtTransactionToastDetailsBodyElement extends Components.DrtTransactionToastDetailsBody, HTMLStencilElement {
    }
    var HTMLDrtTransactionToastDetailsBodyElement: {
        prototype: HTMLDrtTransactionToastDetailsBodyElement;
        new (): HTMLDrtTransactionToastDetailsBodyElement;
    };
    interface HTMLDrtTransactionToastProgressElement extends Components.DrtTransactionToastProgress, HTMLStencilElement {
    }
    var HTMLDrtTransactionToastProgressElement: {
        prototype: HTMLDrtTransactionToastProgressElement;
        new (): HTMLDrtTransactionToastProgressElement;
    };
    interface HTMLDrtTransactionsTableElement extends Components.DrtTransactionsTable, HTMLStencilElement {
    }
    var HTMLDrtTransactionsTableElement: {
        prototype: HTMLDrtTransactionsTableElement;
        new (): HTMLDrtTransactionsTableElement;
    };
    interface HTMLDrtTrimElement extends Components.DrtTrim, HTMLStencilElement {
    }
    var HTMLDrtTrimElement: {
        prototype: HTMLDrtTrimElement;
        new (): HTMLDrtTrimElement;
    };
    interface HTMLDrtUnlockPanelElement extends Components.DrtUnlockPanel, HTMLStencilElement {
    }
    var HTMLDrtUnlockPanelElement: {
        prototype: HTMLDrtUnlockPanelElement;
        new (): HTMLDrtUnlockPanelElement;
    };
    interface HTMLDrtWalletConnectElement extends Components.DrtWalletConnect, HTMLStencilElement {
    }
    var HTMLDrtWalletConnectElement: {
        prototype: HTMLDrtWalletConnectElement;
        new (): HTMLDrtWalletConnectElement;
    };
    interface HTMLDrtWalletConnectAppGalleryIconElement extends Components.DrtWalletConnectAppGalleryIcon, HTMLStencilElement {
    }
    var HTMLDrtWalletConnectAppGalleryIconElement: {
        prototype: HTMLDrtWalletConnectAppGalleryIconElement;
        new (): HTMLDrtWalletConnectAppGalleryIconElement;
    };
    interface HTMLDrtWalletConnectAppStoreIconElement extends Components.DrtWalletConnectAppStoreIcon, HTMLStencilElement {
    }
    var HTMLDrtWalletConnectAppStoreIconElement: {
        prototype: HTMLDrtWalletConnectAppStoreIconElement;
        new (): HTMLDrtWalletConnectAppStoreIconElement;
    };
    interface HTMLDrtWalletConnectDownloadElement extends Components.DrtWalletConnectDownload, HTMLStencilElement {
    }
    var HTMLDrtWalletConnectDownloadElement: {
        prototype: HTMLDrtWalletConnectDownloadElement;
        new (): HTMLDrtWalletConnectDownloadElement;
    };
    interface HTMLDrtWalletConnectGooglePlayIconElement extends Components.DrtWalletConnectGooglePlayIcon, HTMLStencilElement {
    }
    var HTMLDrtWalletConnectGooglePlayIconElement: {
        prototype: HTMLDrtWalletConnectGooglePlayIconElement;
        new (): HTMLDrtWalletConnectGooglePlayIconElement;
    };
    interface HTMLDrtWalletConnectScanElementEventMap {
        "downloadClick": any;
    }
    interface HTMLDrtWalletConnectScanElement extends Components.DrtWalletConnectScan, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDrtWalletConnectScanElementEventMap>(type: K, listener: (this: HTMLDrtWalletConnectScanElement, ev: DrtWalletConnectScanCustomEvent<HTMLDrtWalletConnectScanElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDrtWalletConnectScanElementEventMap>(type: K, listener: (this: HTMLDrtWalletConnectScanElement, ev: DrtWalletConnectScanCustomEvent<HTMLDrtWalletConnectScanElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDrtWalletConnectScanElement: {
        prototype: HTMLDrtWalletConnectScanElement;
        new (): HTMLDrtWalletConnectScanElement;
    };
    interface HTMLDrtWalletProviderIconElement extends Components.DrtWalletProviderIcon, HTMLStencilElement {
    }
    var HTMLDrtWalletProviderIconElement: {
        prototype: HTMLDrtWalletProviderIconElement;
        new (): HTMLDrtWalletProviderIconElement;
    };
    interface HTMLElementTagNameMap {
        "drt-address-table": HTMLDrtAddressTableElement;
        "drt-arc-extension-provider-icon": HTMLDrtArcExtensionProviderIconElement;
        "drt-arrow-right-icon": HTMLDrtArrowRightIconElement;
        "drt-brave-extension-provider-icon": HTMLDrtBraveExtensionProviderIconElement;
        "drt-button": HTMLDrtButtonElement;
        "drt-circle-info-icon": HTMLDrtCircleInfoIconElement;
        "drt-copy-button": HTMLDrtCopyButtonElement;
        "drt-custom-toast": HTMLDrtCustomToastElement;
        "drt-data-with-explorer-link": HTMLDrtDataWithExplorerLinkElement;
        "drt-default-transaction-icon-large": HTMLDrtDefaultTransactionIconLargeElement;
        "drt-default-transaction-icon-small": HTMLDrtDefaultTransactionIconSmallElement;
        "drt-dharitri-logo-icon": HTMLDrtDharitriLogoIconElement;
        "drt-dharitri-symbol-icon": HTMLDrtDharitriSymbolIconElement;
        "drt-edge-extension-provider-icon": HTMLDrtEdgeExtensionProviderIconElement;
        "drt-explorer-link": HTMLDrtExplorerLinkElement;
        "drt-extension-provider-icon": HTMLDrtExtensionProviderIconElement;
        "drt-firefox-extension-provider-icon": HTMLDrtFirefoxExtensionProviderIconElement;
        "drt-format-amount": HTMLDrtFormatAmountElement;
        "drt-generic-toast": HTMLDrtGenericToastElement;
        "drt-ledger-confirm": HTMLDrtLedgerConfirmElement;
        "drt-ledger-connect": HTMLDrtLedgerConnectElement;
        "drt-ledger-icon": HTMLDrtLedgerIconElement;
        "drt-ledger-intro": HTMLDrtLedgerIntroElement;
        "drt-ledger-provider-icon": HTMLDrtLedgerProviderIconElement;
        "drt-magnifying-glass-icon": HTMLDrtMagnifyingGlassIconElement;
        "drt-metamask-provider-icon": HTMLDrtMetamaskProviderIconElement;
        "drt-notifications-feed": HTMLDrtNotificationsFeedElement;
        "drt-passkey-provider-icon": HTMLDrtPasskeyProviderIconElement;
        "drt-pending-transactions-panel": HTMLDrtPendingTransactionsPanelElement;
        "drt-preloader": HTMLDrtPreloaderElement;
        "drt-shard-icon": HTMLDrtShardIconElement;
        "drt-sign-transactions-panel": HTMLDrtSignTransactionsPanelElement;
        "drt-simple-toast": HTMLDrtSimpleToastElement;
        "drt-spinner-icon": HTMLDrtSpinnerIconElement;
        "drt-tdharitri-download-qr-icon": HTMLDrtTdharitriDownloadQrIconElement;
        "drt-tdharitri-qr-code-preloader": HTMLDrtTdharitriQrCodePreloaderElement;
        "drt-toast-list": HTMLDrtToastListElement;
        "drt-tooltip": HTMLDrtTooltipElement;
        "drt-transaction-toast": HTMLDrtTransactionToastElement;
        "drt-transaction-toast-content": HTMLDrtTransactionToastContentElement;
        "drt-transaction-toast-details": HTMLDrtTransactionToastDetailsElement;
        "drt-transaction-toast-details-body": HTMLDrtTransactionToastDetailsBodyElement;
        "drt-transaction-toast-progress": HTMLDrtTransactionToastProgressElement;
        "drt-transactions-table": HTMLDrtTransactionsTableElement;
        "drt-trim": HTMLDrtTrimElement;
        "drt-unlock-panel": HTMLDrtUnlockPanelElement;
        "drt-wallet-connect": HTMLDrtWalletConnectElement;
        "drt-wallet-connect-app-gallery-icon": HTMLDrtWalletConnectAppGalleryIconElement;
        "drt-wallet-connect-app-store-icon": HTMLDrtWalletConnectAppStoreIconElement;
        "drt-wallet-connect-download": HTMLDrtWalletConnectDownloadElement;
        "drt-wallet-connect-google-play-icon": HTMLDrtWalletConnectGooglePlayIconElement;
        "drt-wallet-connect-scan": HTMLDrtWalletConnectScanElement;
        "drt-wallet-provider-icon": HTMLDrtWalletProviderIconElement;
    }
}
declare namespace LocalJSX {
    interface DrtAddressTable {
        "accountScreenData"?: IAddressTableData;
        "onAccessWallet"?: (event: DrtAddressTableCustomEvent<any>) => void;
        "onPageChange"?: (event: DrtAddressTableCustomEvent<number>) => void;
        "onSelectAccount"?: (event: DrtAddressTableCustomEvent<any>) => void;
        "selectedIndex"?: number;
    }
    interface DrtArcExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtArrowRightIcon {
        "class"?: string;
    }
    interface DrtBraveExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtButton {
        /**
          * @default ''
         */
        "class"?: string;
        /**
          * @default ''
         */
        "dataTestId"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onButtonClick"?: (event: DrtButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'large'
         */
        "size"?: `${ButtonSizeEnum}`;
        /**
          * @default 'primary'
         */
        "variant"?: `${ButtonVariantEnum}`;
    }
    interface DrtCircleInfoIcon {
        "class"?: string;
    }
    interface DrtCopyButton {
        "class"?: string;
        "iconClass"?: string;
        "text"?: string;
    }
    interface DrtCustomToast {
        "onDeleteToast"?: (event: DrtCustomToastCustomEvent<string>) => void;
        "toast"?: IComponentToast;
    }
    interface DrtDataWithExplorerLink {
        "class"?: string;
        "data"?: string;
        "dataTestId"?: string;
        "explorerLink"?: string;
        /**
          * @default true
         */
        "showCopyButton"?: boolean;
        /**
          * @default true
         */
        "showExplorerButton"?: boolean;
        /**
          * @default false
         */
        "withTooltip"?: boolean;
    }
    interface DrtDefaultTransactionIconLarge {
        "class"?: string;
    }
    interface DrtDefaultTransactionIconSmall {
        "class"?: string;
    }
    interface DrtDharitriLogoIcon {
        "class"?: string;
    }
    interface DrtDharitriSymbolIcon {
        "class"?: string;
    }
    interface DrtEdgeExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtExplorerLink {
        "class"?: string;
        "dataTestId"?: string;
        "iconClass"?: string;
        "link"?: string;
    }
    interface DrtExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtFirefoxExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface DrtFormatAmount {
        "class"?: string;
        "dataTestId"?: string;
        "decimalClass"?: string;
        "isValid"?: boolean;
        "label"?: string;
        "labelClass"?: string;
        /**
          * @default true
         */
        "showLabel"?: boolean;
        "valueDecimal"?: string;
        "valueInteger"?: string;
    }
    interface DrtGenericToast {
        "onDeleteToast"?: (event: DrtGenericToastCustomEvent<string>) => void;
        "toast"?: CustomToastType;
    }
    interface DrtLedgerConfirm {
        "confirmScreenData"?: IConfirmScreenData;
    }
    interface DrtLedgerConnect {
        /**
          * @default {     accountScreenData: null,     confirmScreenData: null,     connectScreenData: {},   }
         */
        "data"?: ILedgerConnectPanelData;
    }
    interface DrtLedgerIcon {
        "class"?: string;
    }
    interface DrtLedgerIntro {
        "connectScreenData"?: IConnectScreenData;
        /**
          * @default false
         */
        "isAwaiting"?: boolean;
        "onConnect"?: (event: DrtLedgerIntroCustomEvent<any>) => void;
    }
    interface DrtLedgerProviderIcon {
        "class"?: string;
    }
    interface DrtMagnifyingGlassIcon {
        "class"?: string;
    }
    interface DrtMetamaskProviderIcon {
        "class"?: string;
    }
    interface DrtNotificationsFeed {
    }
    interface DrtPasskeyProviderIcon {
        "class"?: string;
    }
    interface DrtPendingTransactionsPanel {
    }
    interface DrtPreloader {
        "class"?: string;
    }
    interface DrtShardIcon {
        "class"?: string;
        /**
          * @default 0
         */
        "shard"?: number;
    }
    interface DrtSignTransactionsPanel {
    }
    interface DrtSimpleToast {
        "onDeleteToast"?: (event: DrtSimpleToastCustomEvent<void>) => void;
        "toast"?: ISimpleToast;
    }
    interface DrtSpinnerIcon {
        "class"?: string;
    }
    interface DrtTdharitriDownloadQrIcon {
        /**
          * @default ''
         */
        "class"?: string;
    }
    interface DrtTdharitriQrCodePreloader {
        "class"?: string;
    }
    interface DrtToastList {
    }
    interface DrtTooltip {
        "class"?: string;
        "onTriggerRender"?: (event: DrtTooltipCustomEvent<boolean>) => void;
        /**
          * @default 'top'
         */
        "position"?: 'top' | 'bottom';
        "trigger"?: HTMLElement;
        /**
          * @default false
         */
        "triggerOnClick"?: boolean;
    }
    interface DrtTransactionToast {
        "fullWidth"?: boolean;
        "onDeleteToast"?: (event: DrtTransactionToastCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "processedTransactionsStatus"?: string | JSX.Element;
        "toastDataState"?: IToastDataState;
        /**
          * @default ''
         */
        "toastId"?: string;
        "transactionProgressState"?: ITransactionProgressState;
        /**
          * @default []
         */
        "transactions"?: ITransactionListItem[];
        "wrapperClass"?: string;
    }
    interface DrtTransactionToastContent {
        "fullWidth"?: boolean;
        "onDeleteToast"?: (event: DrtTransactionToastContentCustomEvent<void>) => void;
        "processedTransactionsStatus"?: string | JSX.Element;
        "toastDataState"?: IToastDataState;
        "transactions"?: ITransactionListItem[];
    }
    interface DrtTransactionToastDetails {
        /**
          * @default 5
         */
        "maxShownTransactions"?: number;
        "processedTransactionsStatus"?: string | JSX.Element;
        "transactionClass"?: string;
        "transactions"?: ITransactionListItem[];
    }
    interface DrtTransactionToastDetailsBody {
        "hash"?: string;
        "index"?: string;
        "link"?: string;
        "status"?: `${TransactionStatusEnum}`;
        /**
          * @default 'transaction-details-list-item'
         */
        "transactionClass"?: string;
    }
    interface DrtTransactionToastProgress {
        "endTime"?: number;
        "isStatusPending"?: boolean;
        "startTime"?: number;
        "toastId"?: string;
    }
    interface DrtTransactionsTable {
        "class"?: string;
        "transactions"?: TransactionRowType[];
    }
    interface DrtTrim {
        "class"?: string;
        /**
          * @default DataTestIdsEnum.trim
         */
        "dataTestId"?: string;
        "text"?: string;
    }
    interface DrtUnlockPanel {
    }
    interface DrtWalletConnect {
        /**
          * @default { wcURI: '' }
         */
        "data"?: IWalletConnectPanelData;
        /**
          * @default ''
         */
        "qrCodeSvg"?: string;
    }
    interface DrtWalletConnectAppGalleryIcon {
        "class"?: string;
    }
    interface DrtWalletConnectAppStoreIcon {
        "class"?: string;
    }
    interface DrtWalletConnectDownload {
        "class"?: string;
    }
    interface DrtWalletConnectGooglePlayIcon {
        "class"?: string;
    }
    interface DrtWalletConnectScan {
        "class"?: string;
        "onDownloadClick"?: (event: DrtWalletConnectScanCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "qrCodeSvg"?: string;
        /**
          * @default ''
         */
        "walletConnectDeepLink"?: string;
    }
    interface DrtWalletProviderIcon {
        "class"?: string;
    }
    interface IntrinsicElements {
        "drt-address-table": DrtAddressTable;
        "drt-arc-extension-provider-icon": DrtArcExtensionProviderIcon;
        "drt-arrow-right-icon": DrtArrowRightIcon;
        "drt-brave-extension-provider-icon": DrtBraveExtensionProviderIcon;
        "drt-button": DrtButton;
        "drt-circle-info-icon": DrtCircleInfoIcon;
        "drt-copy-button": DrtCopyButton;
        "drt-custom-toast": DrtCustomToast;
        "drt-data-with-explorer-link": DrtDataWithExplorerLink;
        "drt-default-transaction-icon-large": DrtDefaultTransactionIconLarge;
        "drt-default-transaction-icon-small": DrtDefaultTransactionIconSmall;
        "drt-dharitri-logo-icon": DrtDharitriLogoIcon;
        "drt-dharitri-symbol-icon": DrtDharitriSymbolIcon;
        "drt-edge-extension-provider-icon": DrtEdgeExtensionProviderIcon;
        "drt-explorer-link": DrtExplorerLink;
        "drt-extension-provider-icon": DrtExtensionProviderIcon;
        "drt-firefox-extension-provider-icon": DrtFirefoxExtensionProviderIcon;
        "drt-format-amount": DrtFormatAmount;
        "drt-generic-toast": DrtGenericToast;
        "drt-ledger-confirm": DrtLedgerConfirm;
        "drt-ledger-connect": DrtLedgerConnect;
        "drt-ledger-icon": DrtLedgerIcon;
        "drt-ledger-intro": DrtLedgerIntro;
        "drt-ledger-provider-icon": DrtLedgerProviderIcon;
        "drt-magnifying-glass-icon": DrtMagnifyingGlassIcon;
        "drt-metamask-provider-icon": DrtMetamaskProviderIcon;
        "drt-notifications-feed": DrtNotificationsFeed;
        "drt-passkey-provider-icon": DrtPasskeyProviderIcon;
        "drt-pending-transactions-panel": DrtPendingTransactionsPanel;
        "drt-preloader": DrtPreloader;
        "drt-shard-icon": DrtShardIcon;
        "drt-sign-transactions-panel": DrtSignTransactionsPanel;
        "drt-simple-toast": DrtSimpleToast;
        "drt-spinner-icon": DrtSpinnerIcon;
        "drt-tdharitri-download-qr-icon": DrtTdharitriDownloadQrIcon;
        "drt-tdharitri-qr-code-preloader": DrtTdharitriQrCodePreloader;
        "drt-toast-list": DrtToastList;
        "drt-tooltip": DrtTooltip;
        "drt-transaction-toast": DrtTransactionToast;
        "drt-transaction-toast-content": DrtTransactionToastContent;
        "drt-transaction-toast-details": DrtTransactionToastDetails;
        "drt-transaction-toast-details-body": DrtTransactionToastDetailsBody;
        "drt-transaction-toast-progress": DrtTransactionToastProgress;
        "drt-transactions-table": DrtTransactionsTable;
        "drt-trim": DrtTrim;
        "drt-unlock-panel": DrtUnlockPanel;
        "drt-wallet-connect": DrtWalletConnect;
        "drt-wallet-connect-app-gallery-icon": DrtWalletConnectAppGalleryIcon;
        "drt-wallet-connect-app-store-icon": DrtWalletConnectAppStoreIcon;
        "drt-wallet-connect-download": DrtWalletConnectDownload;
        "drt-wallet-connect-google-play-icon": DrtWalletConnectGooglePlayIcon;
        "drt-wallet-connect-scan": DrtWalletConnectScan;
        "drt-wallet-provider-icon": DrtWalletProviderIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "drt-address-table": LocalJSX.DrtAddressTable & JSXBase.HTMLAttributes<HTMLDrtAddressTableElement>;
            "drt-arc-extension-provider-icon": LocalJSX.DrtArcExtensionProviderIcon & JSXBase.HTMLAttributes<HTMLDrtArcExtensionProviderIconElement>;
            "drt-arrow-right-icon": LocalJSX.DrtArrowRightIcon & JSXBase.HTMLAttributes<HTMLDrtArrowRightIconElement>;
            "drt-brave-extension-provider-icon": LocalJSX.DrtBraveExtensionProviderIcon & JSXBase.HTMLAttributes<HTMLDrtBraveExtensionProviderIconElement>;
            "drt-button": LocalJSX.DrtButton & JSXBase.HTMLAttributes<HTMLDrtButtonElement>;
            "drt-circle-info-icon": LocalJSX.DrtCircleInfoIcon & JSXBase.HTMLAttributes<HTMLDrtCircleInfoIconElement>;
            "drt-copy-button": LocalJSX.DrtCopyButton & JSXBase.HTMLAttributes<HTMLDrtCopyButtonElement>;
            "drt-custom-toast": LocalJSX.DrtCustomToast & JSXBase.HTMLAttributes<HTMLDrtCustomToastElement>;
            "drt-data-with-explorer-link": LocalJSX.DrtDataWithExplorerLink & JSXBase.HTMLAttributes<HTMLDrtDataWithExplorerLinkElement>;
            "drt-default-transaction-icon-large": LocalJSX.DrtDefaultTransactionIconLarge & JSXBase.HTMLAttributes<HTMLDrtDefaultTransactionIconLargeElement>;
            "drt-default-transaction-icon-small": LocalJSX.DrtDefaultTransactionIconSmall & JSXBase.HTMLAttributes<HTMLDrtDefaultTransactionIconSmallElement>;
            "drt-dharitri-logo-icon": LocalJSX.DrtDharitriLogoIcon & JSXBase.HTMLAttributes<HTMLDrtDharitriLogoIconElement>;
            "drt-dharitri-symbol-icon": LocalJSX.DrtDharitriSymbolIcon & JSXBase.HTMLAttributes<HTMLDrtDharitriSymbolIconElement>;
            "drt-edge-extension-provider-icon": LocalJSX.DrtEdgeExtensionProviderIcon & JSXBase.HTMLAttributes<HTMLDrtEdgeExtensionProviderIconElement>;
            "drt-explorer-link": LocalJSX.DrtExplorerLink & JSXBase.HTMLAttributes<HTMLDrtExplorerLinkElement>;
            "drt-extension-provider-icon": LocalJSX.DrtExtensionProviderIcon & JSXBase.HTMLAttributes<HTMLDrtExtensionProviderIconElement>;
            "drt-firefox-extension-provider-icon": LocalJSX.DrtFirefoxExtensionProviderIcon & JSXBase.HTMLAttributes<HTMLDrtFirefoxExtensionProviderIconElement>;
            "drt-format-amount": LocalJSX.DrtFormatAmount & JSXBase.HTMLAttributes<HTMLDrtFormatAmountElement>;
            "drt-generic-toast": LocalJSX.DrtGenericToast & JSXBase.HTMLAttributes<HTMLDrtGenericToastElement>;
            "drt-ledger-confirm": LocalJSX.DrtLedgerConfirm & JSXBase.HTMLAttributes<HTMLDrtLedgerConfirmElement>;
            "drt-ledger-connect": LocalJSX.DrtLedgerConnect & JSXBase.HTMLAttributes<HTMLDrtLedgerConnectElement>;
            "drt-ledger-icon": LocalJSX.DrtLedgerIcon & JSXBase.HTMLAttributes<HTMLDrtLedgerIconElement>;
            "drt-ledger-intro": LocalJSX.DrtLedgerIntro & JSXBase.HTMLAttributes<HTMLDrtLedgerIntroElement>;
            "drt-ledger-provider-icon": LocalJSX.DrtLedgerProviderIcon & JSXBase.HTMLAttributes<HTMLDrtLedgerProviderIconElement>;
            "drt-magnifying-glass-icon": LocalJSX.DrtMagnifyingGlassIcon & JSXBase.HTMLAttributes<HTMLDrtMagnifyingGlassIconElement>;
            "drt-metamask-provider-icon": LocalJSX.DrtMetamaskProviderIcon & JSXBase.HTMLAttributes<HTMLDrtMetamaskProviderIconElement>;
            "drt-notifications-feed": LocalJSX.DrtNotificationsFeed & JSXBase.HTMLAttributes<HTMLDrtNotificationsFeedElement>;
            "drt-passkey-provider-icon": LocalJSX.DrtPasskeyProviderIcon & JSXBase.HTMLAttributes<HTMLDrtPasskeyProviderIconElement>;
            "drt-pending-transactions-panel": LocalJSX.DrtPendingTransactionsPanel & JSXBase.HTMLAttributes<HTMLDrtPendingTransactionsPanelElement>;
            "drt-preloader": LocalJSX.DrtPreloader & JSXBase.HTMLAttributes<HTMLDrtPreloaderElement>;
            "drt-shard-icon": LocalJSX.DrtShardIcon & JSXBase.HTMLAttributes<HTMLDrtShardIconElement>;
            "drt-sign-transactions-panel": LocalJSX.DrtSignTransactionsPanel & JSXBase.HTMLAttributes<HTMLDrtSignTransactionsPanelElement>;
            "drt-simple-toast": LocalJSX.DrtSimpleToast & JSXBase.HTMLAttributes<HTMLDrtSimpleToastElement>;
            "drt-spinner-icon": LocalJSX.DrtSpinnerIcon & JSXBase.HTMLAttributes<HTMLDrtSpinnerIconElement>;
            "drt-tdharitri-download-qr-icon": LocalJSX.DrtTdharitriDownloadQrIcon & JSXBase.HTMLAttributes<HTMLDrtTdharitriDownloadQrIconElement>;
            "drt-tdharitri-qr-code-preloader": LocalJSX.DrtTdharitriQrCodePreloader & JSXBase.HTMLAttributes<HTMLDrtTdharitriQrCodePreloaderElement>;
            "drt-toast-list": LocalJSX.DrtToastList & JSXBase.HTMLAttributes<HTMLDrtToastListElement>;
            "drt-tooltip": LocalJSX.DrtTooltip & JSXBase.HTMLAttributes<HTMLDrtTooltipElement>;
            "drt-transaction-toast": LocalJSX.DrtTransactionToast & JSXBase.HTMLAttributes<HTMLDrtTransactionToastElement>;
            "drt-transaction-toast-content": LocalJSX.DrtTransactionToastContent & JSXBase.HTMLAttributes<HTMLDrtTransactionToastContentElement>;
            "drt-transaction-toast-details": LocalJSX.DrtTransactionToastDetails & JSXBase.HTMLAttributes<HTMLDrtTransactionToastDetailsElement>;
            "drt-transaction-toast-details-body": LocalJSX.DrtTransactionToastDetailsBody & JSXBase.HTMLAttributes<HTMLDrtTransactionToastDetailsBodyElement>;
            "drt-transaction-toast-progress": LocalJSX.DrtTransactionToastProgress & JSXBase.HTMLAttributes<HTMLDrtTransactionToastProgressElement>;
            "drt-transactions-table": LocalJSX.DrtTransactionsTable & JSXBase.HTMLAttributes<HTMLDrtTransactionsTableElement>;
            "drt-trim": LocalJSX.DrtTrim & JSXBase.HTMLAttributes<HTMLDrtTrimElement>;
            "drt-unlock-panel": LocalJSX.DrtUnlockPanel & JSXBase.HTMLAttributes<HTMLDrtUnlockPanelElement>;
            "drt-wallet-connect": LocalJSX.DrtWalletConnect & JSXBase.HTMLAttributes<HTMLDrtWalletConnectElement>;
            "drt-wallet-connect-app-gallery-icon": LocalJSX.DrtWalletConnectAppGalleryIcon & JSXBase.HTMLAttributes<HTMLDrtWalletConnectAppGalleryIconElement>;
            "drt-wallet-connect-app-store-icon": LocalJSX.DrtWalletConnectAppStoreIcon & JSXBase.HTMLAttributes<HTMLDrtWalletConnectAppStoreIconElement>;
            "drt-wallet-connect-download": LocalJSX.DrtWalletConnectDownload & JSXBase.HTMLAttributes<HTMLDrtWalletConnectDownloadElement>;
            "drt-wallet-connect-google-play-icon": LocalJSX.DrtWalletConnectGooglePlayIcon & JSXBase.HTMLAttributes<HTMLDrtWalletConnectGooglePlayIconElement>;
            "drt-wallet-connect-scan": LocalJSX.DrtWalletConnectScan & JSXBase.HTMLAttributes<HTMLDrtWalletConnectScanElement>;
            "drt-wallet-provider-icon": LocalJSX.DrtWalletProviderIcon & JSXBase.HTMLAttributes<HTMLDrtWalletProviderIconElement>;
        }
    }
}
